name: CI/CD Angular Docker

on:
  push:
    branches:
      - main  # ou master selon ton repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Installer les dépendances Angular
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build Angular
      - name: Build Angular
        run: npm run build --prod

      # 5️⃣ Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/monapp-angular:latest .

      # 7️⃣ Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/monapp-angular:latest

      # 8️⃣ Déployer sur la VM via SSH
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/argo
            git reset --hard
            git pull origin main
            docker build -t monapp-angular .
            docker stop $(docker ps -q --filter ancestor=monapp-angular) 2>/dev/null || true
            docker run -d -p 8080:80 monapp-angular
